Add Home page mobile version
ReemMohamedAbdelfatah/EgyptJuniorsProgrammingSummit-Capstone-1 pull request #1
Opened 2022-09-22 07:07 UTC by ReemMohamedAbdelfatah

Add Dynamic speaker list and hamburger menu.

2022-09-22 19:17 UTC, ReemMohamedAbdelfatah commented
Recorded video link
https://youtu.be/c3xIdXWYTUs

2022-09-22 20:09 UTC, danmainah requested changes
Hi @ReemMohamedAbdelfatah , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-22 20:09 UTC, danmainah commented on README.md
>  # Design
- [x] [optional] it would have been nicer moving the credit to the "Acknowledgements" section, which is usually below the authors' section

2022-09-22 20:09 UTC, danmainah commented on index.html
> +      <ul class="nav-list">
- [x] @ReemMohamedAbdelfatah great work on your hamburger menu, however, the background color should be transparent or of the same color as the top section background.

2022-09-22 20:09 UTC, danmainah commented on about.html
> +<footer class="footer_section">
- [x] Kindly change the background of your footer section, the about page should have a dark background yours has a white background 
![image](https://user-images.githubusercontent.com/61408860/191837966-5091dbeb-d5db-4895-962f-b2f826c6500a.png)

2022-09-22 20:09 UTC, danmainah commented on index.html
> +  <section class="header-section">
- [x] Kindly check the design of this section the design doesn't match the design given below is a comparison:

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/191838645-86b46aa8-8cea-4dc0-90c0-6a3af5f3cea4.png) |  ![image](https://user-images.githubusercontent.com/61408860/191838687-9f72a301-eab7-4c28-ba43-35fe8026220c.png)

2022-09-22 20:09 UTC, danmainah commented on script.js
> +const speakerCardsItems = [
- [x] Kindly add a description to your speakers below the speaker bio, it's a project requirement.Also ensure the text color matches the design given:

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/191839249-e46d104a-62c7-4e05-ad9e-dbecb07185b9.png) |  ![image](https://user-images.githubusercontent.com/61408860/191839288-a654260f-af21-45d7-a908-7db48b132d29.png)

2022-09-22 20:09 UTC, danmainah commented on about.html
> +    <h3 class="slogan">Together, we build our generation's minds.</h3>
- [ ] Kindly ensure the design of this section matches the design given, below is a comparison:

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/191839758-32623520-3373-452a-85b6-0d61e10fe2c4.png) |  ![image](https://user-images.githubusercontent.com/61408860/191839672-a95e6c5a-9947-423a-b767-3bda67f9a738.png)

2022-09-22 20:09 UTC, danmainah commented on about.html
> +  <img src="assets/images/about2.jpeg" alt="summit 2020 image"/>
- [ ] Kindly check the alignment of your images they should be horizontally aligned not vertically.

2022-09-22 20:09 UTC, danmainah commented on index.html
> +  <h1>Main Program</h1>
- [ ] Kindy ensure your page has only one `h1` header tag, kindly change other similar headers to other header tags.

2022-09-22 20:09 UTC, danmainah commented on about.html
> +  <h1>See the past Egypt Juniors Programming Summits</h1>
- [ ] Kindy ensure your page has only one `h1` header tag, kindly change other similar headers to other header tags.

2022-09-22 20:09 UTC, danmainah commented on index.html
> +      <img src="assets/icons/icons_facebook_f.svg" class="icon" alt=""/>
- [ ] Kindly ensure your page is accessible, by ensuring images contain `alt` attributes.

2022-09-22 20:09 UTC, danmainah commented on about.html
> +      <img src="assets/icons/icons_facebook_f.svg" class="icon" alt=""/>
- [ ] Kindly ensure your page is accessible, by ensuring images contain `alt` attributes.

2022-09-23 09:44 UTC, Qoosim requested changes
#   *Status: Required Changes* :recycle:

Hi @ReemMohamedAbdelfatah, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Top Highlights

-  No linter errors. :heavy_check_mark:
-  Good README file. :heavy_check_mark:
-  Correct GitHub Flow. :heavy_check_mark: 
-   Good commit messages. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

- [ ] As mentioned by the previous reviewer, your footer background color  for about page still remains white. Kindly change it to black color as you have it on the guiding template.

### Your Design for about footer

![your-about-background-footer](https://user-images.githubusercontent.com/26597432/191927634-8d56eca4-2b3f-4c70-98c6-87d807c2139f.png)


### Guiding Template About Footer

![template-about-background-footer](https://user-images.githubusercontent.com/26597432/191927710-99af0eaa-e713-4f43-8af3-873f62e569e3.png)

- [OPTIONAL] This comment is actually optional but highly recommended to implement in your project. Probably while implementing some changes required by the previous reviewer, you broke some line of code and as a result, that caused unwanted line on the main program section of your project. Kindly look into it and fix it. Have a look at it :point_down: 

![your-main-program](https://user-images.githubusercontent.com/26597432/191931915-50bb164f-31f2-440e-a7f0-49dbb846d371.png)

- [OPTIONAL] While trying to test your mobile version for the about page. I have some overlapping sections of your page. I will post the screenshots of those areas. Kindly look into them and fix where necessary. :pray: 

### Your Design for your principal title

![your-mobile-about-section-top](https://user-images.githubusercontent.com/26597432/191934008-08488d69-c57f-4e60-af25-180a5bb5a9ee.png)


### Your design for about middle section

![your-mobile-about-middle-section](https://user-images.githubusercontent.com/26597432/191934084-98dcbaa7-681d-47f1-aea1-517cf314c0dc.png)

2022-09-23 09:44 UTC, Qoosim commented on about.html
> +      <img src="assets/icons/icons_facebook_f.svg" class="icon" alt=""/>
- [ ] As mentioned by the previous reviewer, always make your page accessible by giving all your images, their respective attributes names. Something like, `<img sr"#"  alt="github-icon">`. This is for accessibility purpose.

2022-09-23 09:44 UTC, Qoosim commented on about.html
> +<footer class="footer_section">
- [ ] As suggested by the previous reviewer, the about footer background color is black, but your still remains white. Kindly look into it and change the background color.

### Your Design

![your-about-background-footer](https://user-images.githubusercontent.com/26597432/191929532-4b08297c-3722-482b-8bef-20b43fdcdd34.png)

### Guiding Template

![template-about-background-footer](https://user-images.githubusercontent.com/26597432/191929626-0e9f88b8-d693-45aa-9c2c-a0c40a567966.png)

2022-09-23 09:44 UTC, Qoosim commented on index.html
> +
- [OPTIONAL] It is a convention for the logo on the page to have a link that would redirect the users to the home page when it is clicked on. Kindly add a link that would redirect the users to the home page whenever is clicked on.

2022-09-23 10:38 UTC, danmainah requested changes
Hi @ReemMohamedAbdelfatah , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️ Good design

 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 10:38 UTC, danmainah commented on about.html
> +<footer class="footer_section">
- [ ] @ReemMohamedAbdelfatah I saw your message but since this is a project requirement it can't be waived, its suppose to train developers to be design implementers although sometimes we might even have better ideas of implementation its recommended to stick with the design, hope you will understand. Kindly change the background to a dark background.

2022-09-23 11:04 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @ReemMohamedAbdelfatah 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 11:04 UTC, tresorsawasawa commented on script.js
> +  },
- [ **OPTIONAL** ] **IMPORTANT:** To stick to the **[Behance template design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)**, kindly make sure you add the background image on each `Featured Speaker` photo like in the image below.

### Template Design
![Screenshot from 2022-09-22 12-45-12](https://user-images.githubusercontent.com/83042742/191727298-5c237bed-1ff4-4718-8075-e470aa9c9ce9.png)

### Your Design
![Screenshot from 2022-09-23 13-02-28](https://user-images.githubusercontent.com/83042742/191947149-91e98456-be5a-412b-bd40-c5d0fc5bbae4.png)

2022-09-23 20:16 UTC, merged